[tool.poetry]
name = "frontend-api"
version = "0.1.0"
description = ""
authors = ["MogboPython <mogbo18@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.114.2"
uvicorn = "^0.30.6"
alembic = "^1.13.2"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"
python-dotenv = "^1.0.1"
django = "^5.1.1"
djangorestframework = "^3.15.2"
psycopg2-binary = "^2.9.9"
markdown = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
